### ISSUE TITLE
No CMakeLists.txt file in the turtlebot_description package

### ISSUE THREAD

**Issue by Rohithv-r** [g40st/ROS_maze_challenge#1]
Hey, I was trying to build the package in my catkin workspace, but it shows an error that there is no CMakeLists.txt file in it, only a package.xml exists. 
I saw some .cmake files inside the cmake directory of the turtlebot_description package, (turtlebot_descriptionConfig.cmake and turtlebot_descriptionConfig-version.cmake), but I don't know if they can be used to build the package and if they are the files used to build it, can you tell me how? 
Thanks in advance.

**Comment by g40st** [comment]
Hi, 

I'm not working anymore on this project. Maybe there is a problem with newer versions of ROS.
This package was used on the [ROS Kinetic](http://wiki.ros.org/kinetic/Installation/Ubuntu). Can you test it with this version?

Kind regards.

**Comment by Rohithv-r** [comment]
Yes, I'm working with ROS Kinetic only.. But when I build your package using carkin_make, it shows the error

**Comment by Rohithv-r** [comment]
Can you please guide me on how to build the turtlebot_description package alone?
