### ISSUE TITLE
Turtlebot doesn't move / nothing happens

### ISSUE THREAD

**Issue by taletovic** [g40st/ROS_maze_challenge#2]
Hello,

I did the following just like in the tutorial:

- `export TURTLEBOT_3D_SENSOR=hokuyo`
- `rosrun gazebo_ros spawn_model -file ~/catkin_ws/src/ROS_maze_challenge/maze_practice/model.sdf -sdf -model -maze -x 16 -y 5`

After these steps I have everything in Gazebo loaded:
![Screenshot from 2019-05-24 09-31-37](https://user-images.githubusercontent.com/50860059/58310378-c914d500-7e06-11e9-8e97-5dbd7139e5d2.png)

When I launch the last command:
`roslaunch ch_171744_maze start_maze.launch`

Nothing happens and in the Terminal I have the following:

`[INFO] [1558683162.052747, 18.730000]: start Maze Solver Node`

![Screenshot from 2019-05-24 09-32-47](https://user-images.githubusercontent.com/50860059/58310532-1f821380-7e07-11e9-92eb-1fba91b82127.png)

**Comment by g40st** [comment]
Hi,

sorry for the late answer. I'm on a roadtrip. 

Can you move the robot with the keyboard:
roslaunch turtlebot_teleop keyboard_teleop.launch

You need to use the keys that are printed at the console. 

Greets

**Comment by taletovic** [comment]
Hello, thank you for your quick answer.

I've noticed that the library:
[https://github.com/turtlebot/turtlebot_simulator](url)
doesn't have the kinetic branch and I was just cloning into with:
`git clone https://github.com/turtlebot/turtlebot_simulator`
And tried to run it from my catkin workspace. It didn't work, not even with `turtlebot_teleop`.

Then I followed your steps and installed the package using:
`sudo apt-get install ros-kinetic-turtlebot`
which installed `ros-kinetic-turtlebot-gazebo` too.

I used:
`cd /opt/ros/kinetic/share`
`sudo rm -r turtlebot_description`
`sudo mv turtlebot_description /opt/ros/kinetic/share`

It still didn't work with `turtlebot_teleop`.

Then I reinstalled `sudo apt-get install ros-kinetic-turtlebot` and manually copied these 4 files to ` /opt/ros/kinetic/shareturtlebot_description`:

- turtlebot_description/urdf/turtlebot_gazebo.urdf.xacro
- turtlebot_description/urdf/sensors/hokuyo.urdf.xacro
- turtlebot_description/robots/kobuki_hexagons_hokuyo.urdf
- turtlebot_description/meshes/sensors/hokuyo.dae

I noticed that in the turtlebot_description/robots/kobuki_hexagons_hokuyo.urdf:
```
<?xml version="1.0"?>
<!--
    - Base      : kobuki
    - Stacks    : hexagons
    - 3d Sensor : hokuyo
-->    
<robot name="turtlebot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find turtlebot_description)/urdf/turtlebot_common_library.urdf.xacro" />
  <xacro:include filename="$(find kobuki_description)/urdf/kobuki.urdf.xacro" />
  <xacro:include filename="$(find turtlebot_description)/urdf/stacks/hexagons.urdf.xacro"/>
  <xacro:include filename="$(find turtlebot_description)/urdf/sensors/kinect.urdf.xacro"/>
  
  <kobuki/>
  <stack_hexagons parent="base_link"/>
  <sensor_hokuyo  parent="base_link"/>
</robot>
```
I changed the line `<xacro:include filename="$(find turtlebot_description)/urdf/sensors/kinect.urdf.xacro"/>` to:
`<xacro:include filename="$(find turtlebot_description)/urdf/sensors/hokuyo.urdf.xacro"/>`

And it suddenly worked.

Maybe you can test it yourself and if so update the package.
Thank you.
